# Generated by Django 4.0.10 on 2025-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_in_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
