# Generated by Django 4.2.1 on 2023-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="overview",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
