# Generated by Django 4.0.10 on 2023-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
