# Generated by Django 4.2.1 on 2023-07-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_overview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="keywords",
            new_name="tags",
        ),
    ]
