# Generated by Django 4.2.1 on 2023-07-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_rename_keywords_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="reading_time",
        ),
    ]
