# Generated by Django 4.0.10 on 2023-08-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at', '-order'), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
