# Generated by Django 4.0.10 on 2023-08-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': 'created_at', 'ordering': ('-order', '-created_at'), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
