# Generated by Django 4.0.10 on 2023-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
