# Generated by Django 4.0.10 on 2023-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
