# Generated by Django 4.0.10 on 2023-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blog_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogviewip',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='blogviewip',
            unique_together={('ip_address', 'blog')},
        ),
    ]
