# Generated by Django 4.2.1 on 2023-06-22 17:18

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0016_alter_certification_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_project_image_path,
                    ),
                ),
                ("short_description", models.CharField(max_length=254)),
                ("technology", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "project",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.AlterField(
            model_name="certification",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.image_upload_helpers.get_project_media_path
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_media",
                        to="portfolios.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Media",
                "verbose_name_plural": "Project Media",
                "db_table": "project_media",
                "get_latest_by": "created_at",
                "order_with_respect_to": "project",
            },
        ),
    ]
