# Generated by Django 4.2.1 on 2023-06-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0021_rename_url_project_github_url_project_preview_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "get_latest_by": "created_at",
                "ordering": ["order"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
