# Generated by Django 4.2.1 on 2023-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0024_interest_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
