# Generated by Django 5.1.7 on 2025-03-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('url', models.URLField(verbose_name='Video URL')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10, verbose_name='Media Type')),
                ('format', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=20, verbose_name='Format')),
                ('media_format', models.CharField(blank=True, choices=[('mp4', 'MP4'), ('mkv', 'MKV'), ('avi', 'AVI'), ('webm', 'WEBM'), ('flv', 'FLV'), ('mov', 'MOV'), ('wmv', 'WMV'), ('ogv', 'OGV'), ('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A'), ('ogg', 'OGG'), ('flac', 'FLAC'), ('aac', 'AAC'), ('opus', 'OPUS')], max_length=10, null=True, verbose_name='Media Format')),
                ('quality', models.CharField(blank=True, choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '4K'), ('4320p', '8K'), ('320kbps', '320kbps'), ('256kbps', '256kbps'), ('128kbps', '128kbps')], max_length=20, null=True, verbose_name='Quality')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Download Request',
                'verbose_name_plural': 'Download Requests',
                'db_table': 'grabit_download_requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
