# Generated by Django 5.1.7 on 2025-03-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='format',
        ),
    ]
