# Generated by Django 4.2.1 on 2023-06-30 19:46

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_code_snippet_image_path,
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Code Snippet",
                "verbose_name_plural": "Code Snippets",
                "db_table": "code_snippet",
                "ordering": ("order", "-created_at"),
                "get_latest_by": "created_at",
            },
        ),
    ]
