# Generated by Django 4.0.10 on 2023-07-10 17:54

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('overview', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helpers.get_code_snippet_image_path)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'verbose_name_plural': 'Code Snippets',
                'db_table': 'code_snippet',
                'ordering': ('order', '-created_at'),
                'get_latest_by': 'created_at',
            },
        ),
    ]
