# Generated by Django 4.2.1 on 2023-06-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_snippets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
