# Generated by Django 4.2.1 on 2023-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_snippets", "0002_codesnippet_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="language",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
