# Generated by Django 4.2.1 on 2023-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_snippets", "0003_codesnippet_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codesnippet",
            name="short_description",
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="overview",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
