# Generated by Django 4.0.10 on 2023-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0003_alter_codesnippet_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
