# Generated by Django 4.0.10 on 2023-08-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0004_codesnippet_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at', '-order'), 'verbose_name': 'Code Snippet', 'verbose_name_plural': 'Code Snippets'},
        ),
    ]
