# Generated by Django 4.0.10 on 2023-08-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0005_alter_codesnippet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'get_latest_by': 'created_at', 'ordering': ('-order', '-created_at'), 'verbose_name': 'Code Snippet', 'verbose_name_plural': 'Code Snippets'},
        ),
    ]
