# Generated by Django 4.0.10 on 2023-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0006_alter_codesnippet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
