# Generated by Django 4.0.10 on 2023-08-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0009_alter_codesnippet_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Published', max_length=20),
        ),
        migrations.CreateModel(
            name='CodeSnippetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='code_snippets.codesnippet')),
            ],
            options={
                'verbose_name': 'Code Snippet Comment',
                'verbose_name_plural': 'Code Snippet Comments',
                'db_table': 'code_snippet_comment',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='CodeSnippetViewIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField(default=False)),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_ips', to='code_snippets.codesnippet')),
            ],
            options={
                'verbose_name': 'Code Snippet View IP',
                'verbose_name_plural': 'Code Snippet View IPs',
                'db_table': 'code_snippet_view_ip',
                'ordering': ('-last_visited_at',),
                'get_latest_by': 'created_at',
                'unique_together': {('ip_address', 'code_snippet')},
            },
        ),
    ]
