# Generated by Django 4.0.10 on 2025-03-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(help_text='Folder path relative to IMAGE_UPLOADS/', max_length=255)),
                ('file_name', models.CharField(help_text='Unique file name for the uploaded image', max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'db_table': 'uploaded_image',
            },
        ),
    ]
