# Generated by Django 4.0.10 on 2025-03-19 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='temp_uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file_name',
            field=models.CharField(help_text='Unique file name for the uploaded image', max_length=255),
        ),
    ]
