# Generated by Django 4.0.10 on 2025-03-19 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_uploadedimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='file_name',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='temp_uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='folder_path',
            field=models.CharField(default='temp/', help_text='Path within IMAGE_UPLOADS/', max_length=255),
        ),
    ]
