# Generated by Django 4.0.10 on 2025-03-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_rename_file_name_uploadedimage_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
