# Generated by Django 4.0.10 on 2025-03-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_uploadedimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
