# Generated by Django 4.0.10 on 2025-03-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
