# Generated by Django 4.0.10 on 2025-03-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('file', models.FileField(upload_to='temp/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('folder_path', models.CharField(default='default/', help_text='Path within FILE_UPLOADS/', max_length=255)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('PDF', 'PDF'), ('Other', 'Other')], default='Image', max_length=50)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'uploaded_files',
                'ordering': ('-created_at',),
            },
        ),
    ]
