# Generated by Django 5.1.7 on 2025-04-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanizerAiUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Humanizer AI Utils',
                'verbose_name_plural': 'Humanizer AI Utils',
                'db_table': 'humanizer_ai_utils',
                'ordering': ('-created_at',),
            },
        ),
    ]
