# Generated by Django 5.1.7 on 2025-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_humanizeraiutils'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumanizerAiUtils',
        ),
    ]
