# Generated by Django 4.2.1 on 2023-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_portfolio_user",
            field=models.BooleanField(default=False),
        ),
    ]
