# Generated by Django 4.2.1 on 2023-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_nick_name_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="resume_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
