# Generated by Django 4.2.1 on 2023-06-15 17:25

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfessionalExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("company", models.CharField(max_length=150)),
                (
                    "company_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_professional_experience_company_image_path,
                    ),
                ),
                ("company_url", models.URLField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=254, null=True)),
                ("designation", models.CharField(max_length=150)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Contractual", "Contractual"),
                            ("Remote", "Remote"),
                        ],
                        default="Full Time",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Professional Experience",
                "verbose_name_plural": "Professional Experiences",
                "db_table": "professional_experience",
                "ordering": ("-currently_working", "-start_date"),
                "get_latest_by": "created_at",
            },
        ),
    ]
