# Generated by Django 4.2.1 on 2023-06-15 19:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalexperience",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
