# Generated by Django 4.2.1 on 2023-06-16 16:53

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0002_alter_professionalexperience_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=150, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_skill_image_path,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            ("None", "-----"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        default="None",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skill",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.AlterField(
            model_name="professionalexperience",
            name="company",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
