# Generated by Django 4.2.1 on 2023-06-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_alter_skill_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "get_latest_by": "created_at",
                "ordering": ("order", "-created_at"),
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
    ]
