# Generated by Django 4.2.1 on 2023-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0005_alter_skill_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "-----"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="0",
                null=True,
            ),
        ),
    ]
