# Generated by Django 4.2.1 on 2023-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0006_alter_skill_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default=None,
                null=True,
            ),
        ),
    ]
