# Generated by Django 4.2.1 on 2023-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0007_alter_skill_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
