# Generated by Django 4.2.1 on 2023-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0008_alter_skill_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
