# Generated by Django 4.2.1 on 2023-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0009_alter_skill_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalexperience",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
