# Generated by Django 4.2.1 on 2023-06-17 06:16

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0010_alter_professionalexperience_slug_alter_skill_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_education_school_image_path,
                    ),
                ),
                ("degree", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=254, null=True)),
                ("field_of_study", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_studying", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=254, null=True)),
                ("activities", models.CharField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "db_table": "education",
                "ordering": ("-end_date", "-created_at"),
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="EducationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.image_upload_helpers.get_education_media_path
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_media",
                        to="portfolios.education",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Media",
                "verbose_name_plural": "Education Media",
                "db_table": "education_media",
                "get_latest_by": "created_at",
                "order_with_respect_to": "education",
            },
        ),
    ]
