# Generated by Django 4.2.1 on 2023-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0011_education_educationmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="educationmedia",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
