# Generated by Django 4.2.1 on 2023-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0012_alter_education_slug_alter_educationmedia_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationmedia",
            name="title",
            field=models.CharField(default="Media Sample", max_length=150),
            preserve_default=False,
        ),
    ]
