# Generated by Django 4.2.1 on 2023-06-17 09:41

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0014_certification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.image_upload_helpers.get_education_media_path
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_media",
                        to="portfolios.certification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification Media",
                "verbose_name_plural": "Certification Media",
                "db_table": "certification_media",
                "get_latest_by": "created_at",
                "order_with_respect_to": "certification",
            },
        ),
    ]
