# Generated by Django 4.2.1 on 2023-06-17 09:49

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0015_certificationmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.image_upload_helpers.get_certification_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="certificationmedia",
            name="file",
            field=models.FileField(
                upload_to=utils.image_upload_helpers.get_certification_media_path
            ),
        ),
    ]
