# Generated by Django 4.2.1 on 2023-06-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0017_project_alter_certification_title_projectmedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificationmedia",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="certificationmedia",
            name="description",
        ),
        migrations.RemoveField(
            model_name="certificationmedia",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="certificationmedia",
            name="title",
        ),
        migrations.RemoveField(
            model_name="certificationmedia",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="educationmedia",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="educationmedia",
            name="description",
        ),
        migrations.RemoveField(
            model_name="educationmedia",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="educationmedia",
            name="title",
        ),
        migrations.RemoveField(
            model_name="educationmedia",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="projectmedia",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="projectmedia",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projectmedia",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="projectmedia",
            name="updated_at",
        ),
    ]
