# Generated by Django 4.2.1 on 2023-06-22 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0018_remove_certificationmedia_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationmedia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificationmedia",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificationmedia",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="certificationmedia",
            name="title",
            field=models.CharField(default="Example", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificationmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="educationmedia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="educationmedia",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="educationmedia",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="educationmedia",
            name="title",
            field=models.CharField(default="Example", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="educationmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="title",
            field=models.CharField(default="Example", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
