# Generated by Django 4.2.1 on 2023-06-22 17:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0019_certificationmedia_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
