# Generated by Django 4.2.1 on 2023-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0020_project_order_alter_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="url",
            new_name="github_url",
        ),
        migrations.AddField(
            model_name="project",
            name="preview_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
