# Generated by Django 4.2.1 on 2023-06-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0022_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalexperience",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-present", "-start_date"),
                "verbose_name": "Professional Experience",
                "verbose_name_plural": "Professional Experiences",
            },
        ),
        migrations.RenameField(
            model_name="education",
            old_name="currently_studying",
            new_name="present",
        ),
        migrations.RenameField(
            model_name="professionalexperience",
            old_name="currently_working",
            new_name="present",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="currently_working",
            new_name="present",
        ),
    ]
