# Generated by Django 4.2.1 on 2023-06-26 14:15

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0023_alter_professionalexperience_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_interest_image_path,
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
                "db_table": "interest",
                "ordering": ("order", "-created_at"),
                "get_latest_by": "created_at",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "get_latest_by": "created_at",
                "ordering": ("order", "-created_at"),
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
