# Generated by Django 4.2.1 on 2023-06-26 15:20

from django.db import migrations, models
import utils.image_upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0025_alter_interest_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_upload_helpers.get_movie_image_path,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("watched", models.BooleanField(default=True)),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movie",
                "ordering": ("-updated_at",),
                "get_latest_by": "created_at",
            },
        ),
    ]
